FROM gcc:latest

RUN mkdir -p /usr/local/include/c++/16.1.0/x86_64-linux-gnu/bits && \
    g++ -std=c++17 -x c++-header /usr/local/include/c++/16.1.0/x86_64-linux-gnu/bits/stdc++.h \
    -o /usr/local/include/c++/16.1.0/x86_64-linux-gnu/bits/stdc++.h.gch